networks:
  abri-proxy:
    name: abri-proxy 
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.12.0/24
         gateway: 192.168.12.1
services:
  dnsmasq:
    container_name: abri-dns
    restart: always
    image: jpillora/dnsmasq:1.1

    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "50"
    environment:
      - "HTTP_USER=masoud"
      - "HTTP_PASS=masoud"
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
      - ./dnsmasq/domains.conf:/etc/dnsmasq.d/domains.conf
    ports:
      - "53:53/udp"
      - "5380:8080"
    cap_add:
      - NET_ADMIN
    networks:
      - abri-proxy

  nginx-proxy:
    image: nginx:latest
    container_name: abri-nginx
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "50"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/allowed_ips.conf:/etc/nginx/allowed_ips.conf:rw
      - ./nginx/logs:/var/log/nginx/
    networks:
      - abri-proxy
