services:
  dnsmasq:
    container_name: abri-dns
    restart: always
    image: jpillora/dnsmasq:1.1

    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "50"
    environment:
      - "HTTP_USER=masoud"
      - "HTTP_PASS=masoud"
    volumes:
      - ./dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf
      - ./dnsmasq/proxy.conf:/etc/dnsmasq.d/proxy.conf
    ports:
      - "53:53/udp"
      - "5380:8080"
    cap_add:
      - NET_ADMIN
      
  nginx-proxy:
    image: nginx:latest
    container_name: abri-nginx
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "50"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
